### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by czmik** [Jenik5/azrouter#1]
<img width="531" height="319" alt="Image" src="https://github.com/user-attachments/assets/b99167b2-67a4-4d78-98a0-451529647dec" />

**Comment by Jenik5** [comment]
hacs.json added. It should work now.
Thanks for letting me know.

**Comment by czmik** [comment]
Hi,
Unfortunatelly still the same. Only changed commit number in error message.
Aditionally after adding own repository to HACS and reboot HA, repository
address leasing from settings.
Thanks and regards,
Míla

Dne ne 16. 11. 2025 8:04 uživatel Jenik5 ***@***.***> napsal:

**Comment by Jenik5** [comment]
Hi, thanks a lot for reporting this!

The issue with HACS installation is now fully resolved.

The integration has been tested independently and confirmed working.

It is now available directly in the HACS store (no custom repository required anymore).

The repository structure was corrected and validated by HACS.

The README has also been updated with the correct installation and configuration instructions.

If you still see any unexpected behavior, please let me know — happy to help.
Thanks again for testing and for your feedback!

**Comment by czmik** [comment]
Nice! It works. Thank you very much for this project. It is very helpfull. I will regurarly use it and if I found any issue or will have some idea, I will write about it. If I can help you in any other way, let me know.

**Comment by Jenik5** [comment]
Nice to hear it. 
I will definitely extend the wallbox.
Btw. What devices do you have?

**Comment by czmik** [comment]
I have in daily use:
1. Central unit AZ Router Smart
2. AZ Router Slave for boiler
3. AZ Charger Cube

Dne ne 16. 11. 2025 20:48 uživatel Jenik5 ***@***.***> napsal:
